### ISSUE TITLE
Error in importing pre-trained T5 model

### ISSUE THREAD

**Issue by biochorl** [kWeissenow/ProtT5dst#1]
Hi, it is not clear what I am doing wrong at this point of the predict.py script:
def get_T5_model(t5_dir):
    if 'xxl' in t5_dir.name:
        transformer_link = "Rostlab/prot_t5_xxl_uniref50"
    elif 'xl' in t5_dir.name:
        transformer_link = "Rostlab/prot_t5_xl_uniref50"
    else:
        raise NotImplementedError

it raises the "NotImplementedError"
when defining the T5_model.

I downloaded and unpacked the pre-trained models in the same folder of the rest of the files;
the script requires to link the folders containing the checkpoint files. I linked the model folders.
 Anyway, I don't notice the presence of files with the name suffixes listed in the script above (including "xxl" or "xl")
after unpacking the Prot-T5 and AMBER2 pre-trained models.

What files/folder should I link as input?
Thanks

**Comment by kWeissenow** [comment]
I'm sorry for the confusion. This was indeed not implemented in a very straightforward way.
I updated the scripts to not require any manual download anymore. Please clone the repo again and try running your inference as shown in the README. The ProtT5 model should be downloaded automatically.
Please let me know how it goes and in case you need any further support!

**Comment by biochorl** [comment]
Thanks!
The issue is solved, there is just the need to
install the "sentencepiece" package as prompts it is missing before starting computation.
I did it by  "pip install sentencepiece" and everything works,
Best WIshes
